Set name and department on update
senior-knights/course-schedulizer pull request #154
Opened 2021-03-17 13:20 UTC by Jonri2

Fixes a bug where name and department would not update. To test, click on a section and edit its name and department. Then, click on the same section again or any section from the same course and the changes should have persisted.

2021-03-17 13:22 UTC, charkour commented
Thanks for this. Looks like there is an issue with the tests. Probably due to the changes to the test files in a previous PR.

2021-03-17 13:26 UTC, Jonri2 commented
No. It's because our test file has 2 sections of MATH-390 with different names and this PR makes it take the second one instead of the 1st one. Both are incorrect though. I'm not really sure how to deal with that. Any ideas?

2021-03-17 13:49 UTC, charkour commented
I don't have any initial thoughts. That's an interesting problem. I can look into it later.

2021-03-17 13:53 UTC, Jonri2 commented
> I don't have any initial thoughts. That's an interesting problem. I can look into it later.

Yeah, I think that it is incorrect to have 2 different names for the same course in which case it's just the spreadsheet that is wrong, but we can ask Prof. Pruim what behavior he would expect.

2021-03-17 13:53 UTC, rpruim commented
FYI: 390 is an interesting thing: Eventually it gets two instructors.  But since that looks like a conflict, I assign one each semester as I'm creating the schedule and then I let the registrar know it is both both semesters.  That's a work-around, not ideal behavior.

When you say name do you mean course title?

2021-03-17 13:55 UTC, rpruim commented
A course like Math 385 (Topics in Mathematics) could have multiple titles.  Next fall it will be called Topics in Mathematics: Optimization.  But it will have different names each time it is offered.  But generally, the title should be the same each time.  Mismatches likely are caused from sloppy typing or from forgetting to update a title when modifying a course number as part of schedule construction.

2021-03-17 14:03 UTC, Jonri2 commented
> FYI: 390 is an interesting thing: Eventually it gets two instructors. But since that looks like a conflict, I assign one each semester as I'm creating the schedule and then I let the registrar know it is both both semesters. That's a work-around, not ideal behavior.
> 
> When you say name do you mean course title?

Yes. One is called Modeling of Angiogenesis and one is called Galois Theory, but our interface currently only allows 1 title for a course so it just picks one of them on import and then both are exported with the same name.

2021-03-17 19:01 UTC, charkour commented
Would it be better if we allow multiple course names to be separated by a semicolon as we do for professors?

2021-03-17 19:03 UTC, charkour requested changes
Would it be better if we allow multiple course names to be separated by a semicolon as we do for professors? Would it be better to add it to a different PR?

2021-03-17 20:25 UTC, Jonri2 commented
> Would it be better if we allow multiple course names to be separated by a semicolon as we do for professors? Would it be better to add it to a different PR?

Perhaps, though that may be confusing. Let's just stick with this and make a low priority issue

2021-03-17 22:34 UTC, charkour commented
Or I'm thinking it maybe be better to assign a name on a per semester basis? Regardless, I'll make an issue and we can figure it out later.

2021-03-18 00:38 UTC, charkour approved these changes
LGTM. 

That's an important two lines of code.

2021-03-18 16:23 UTC, merged