add routing to home, about, help
senior-knights/course-schedulizer pull request #52
Opened 2020-11-23 19:53 UTC by charkour

This adds basic routing to the home page (the main tool), and about page, and a help page. 

There is no styling on the navigation yet. Do you guys have any ideas on how I should look. Maybe styling can be another PR if someone is willing to figure out a good system for navigating. 

closes #41

2020-11-23 20:24 UTC, Jonri2 requested changes
This looks like a good start to me. No need to put too much effort into styling, but I think I'd just prefer to see the links inside the hamburger menu popover if that's possible.

2020-11-23 20:24 UTC, Jonri2 commented on client-course-schedulizer/src/components/App/App.tsx
> +        </nav>
Is it possible to put these links inside the hamburger menu?

2020-11-23 22:58 UTC, charkour commented
Okay, I think that works, but it's a little confusing having different actions in one menu. I'll try it out.

2020-11-24 18:22 UTC, Jonri2 approved these changes
This is awesome! Really well done. It looks pretty slick

2020-11-24 20:04 UTC, merged